### PR TITLE
Fix Makefile.win

### PR DESCRIPTION
**Pull request by cw789**
Reference https://github.com/elixir-sqlite/exqlite/issues/150

@greven
Could you be so kind and test this change?
It was a long day and I'm now on my tablet online only.

So this is my guess. Probably I'll make it tomorrow to test it myself also.

### CODE REVIEW

**Comment by warmwaffles** [comment]
Oh stupid me, `-DD` thanks for figuring this out.

**Review by warmwaffles — APPROVED** [review]

**Review by greven — APPROVED** [review]
This is it! It's working! =)

**Comment by greven** [comment]
Screenshot 2021-05-17 182301

Building fine now! Thanks for finding out what it was. Building anything on Windows is always a pain!

**Comment by cw789** [comment]
> Oh stupid me, `-DD` thanks for figuring this out.

So if it was not on purpose, I'm confident now this should solve the issue.
You're welcome. 🙌

**Pull request merged**
