### PR TITLE
use multi_step in stream

### PR DESCRIPTION
**Pull request by ruslandoga**
👋

This makes `Repo.stream` a bit faster.

```elixir
# although `max_rows: 1` now adds the overhead of `multi_step` compared to prev approach using `step`
iex> :timer.tc fn -> Repo.transaction(fn -> Repo.stream(Word, max_rows: 1) |> Enum.take(500) end); :ok end
{168632, :ok}

iex> :timer.tc fn -> Repo.transaction(fn -> Repo.stream(Word, max_rows: 100) |> Enum.take(500) end); :ok end
{63922, :ok}
```

### CODE REVIEW

**Comment by ruslandoga** [comment]
BTW, I'm getting logs spammed when the stream is being fetched. Is this expected?

```
iex(4)> :timer.tc fn -> Repo.transaction(fn -> Repo.stream(Word, max_rows: 100) |> Enum.take(500) end); :ok end
[debug] QUERY OK db=0.3ms idle=1289.1ms
begin []
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:298
[debug] QUERY OK source="words" db=0.2ms
SELECT w0."user_id", w0."word", w0."pronunciation", w0."senses", w0."inserted_at", w0."updated_at" FROM "words" AS w0 []
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:298
[debug] QUERY OK source="words" db=1.3ms
SELECT w0."user_id", w0."word", w0."pronunciation", w0."senses", w0."inserted_at", w0."updated_at" FROM "words" AS w0 []
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:298
[debug] QUERY OK source="words" db=1.2ms
SELECT w0."user_id", w0."word", w0."pronunciation", w0."senses", w0."inserted_at", w0."updated_at" FROM "words" AS w0 []
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:298
[debug] QUERY OK source="words" db=0.4ms
SELECT w0."user_id", w0."word", w0."pronunciation", w0."senses", w0."inserted_at", w0."updated_at" FROM "words" AS w0 []
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:298
[debug] QUERY OK source="words" db=0.3ms
SELECT w0."user_id", w0."word", w0."pronunciation", w0."senses", w0."inserted_at", w0."updated_at" FROM "words" AS w0 []
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:298
[debug] QUERY OK source="words" db=0.4ms
SELECT w0."user_id", w0."word", w0."pronunciation", w0."senses", w0."inserted_at", w0."updated_at" FROM "words" AS w0 []
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:298
[debug] QUERY OK source="words" db=0.0ms
SELECT w0."user_id", w0."word", w0."pronunciation", w0."senses", w0."inserted_at", w0."updated_at" FROM "words" AS w0 []
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:298
[debug] QUERY OK db=0.0ms
commit []
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:298
{63922, :ok}
```

**Comment by warmwaffles** [comment]
Oh I didn't even realize `max_rows` was an existing option. We should deprecate the `chunk_size` and emit a warning if it is used.

**Comment by warmwaffles** [comment]
Also I wonder why I didn't use `multi_step` in the `handle_fetch` call.

**Comment by warmwaffles** [comment]
@ruslandoga I'll get to this soon. I think this is a good change.

**Pull request merged**
