### PR TITLE
Pass binary filename to sqlite3_open

### PR DESCRIPTION
**Pull request by greg-rychlewski**
Closes https://github.com/elixir-sqlite/exqlite/issues/277

This looks like it's your issue since Elixir strings at UTF-8 encoded. But I have to admit I'm not sure why it was latin-1 before. So I might be stepping on a landmine without knowing it.

### CODE REVIEW

**Comment by greg-rychlewski** [comment]
Ok I learned very quickly why it was `ERL_NIF_LATIN1` before. It's because `ERL_NIF-UTF8` is new. So instead of passing it as a charlist I pass it as a binary and then convert it to a proper null terminated string inside the nif.

**Comment by greg-rychlewski** [comment]
i'm pretty sure the failures are race conditions because they were not touched in this pr

**Comment by greg-rychlewski** [comment]
I guess it's not a race condition =(

**Comment by warmwaffles** [comment]
I'll take a look at this later in the evening.

**Comment by warmwaffles** [comment]
This _may_ be an issue with how the filesystem represents utf8 characters in windows. I'm not a windows dev, but I think we'll need to dig in to wchar stuff for the filesystem. I suspect it's utf16.

**Comment by warmwaffles** [comment]
@greg-rychlewski it's been a while, can you try re-running the CI. I can't see where to kick it off on my end.

**Comment by greg-rychlewski** [comment]
@warmwaffles done

**Pull request closed without merging**
