### PR TITLE
Mirror SQLITE flags for Makefile.win

### LINKED ISSUE #130: Ensure same SQLITE flags across Makefile and Makefile.win
I notice that `Makefile.win` does not have any of our SQLite flags that we pass to the Unix equivalent, unless I am missing something. We will want to make sure those are the same for consistency.

### PR DESCRIPTION
**Pull request by cw789**
This is my first time editing a Makefile.win.
So we should handle this with care.

Close #130

### CODE REVIEW

**Comment by cw789** [comment]
I probably should check this all a second time, so marked it as draft for now.

**Comment by warmwaffles** [comment]
This looks good to me so far. @cw789 I would love if you could give it a shot.

**Comment by cw789** [comment]
I want to check the following things before (this week):

- why `Wall` isn't working
- what's `EHsc` about
- the differents between `O2` and `O3`
- remove the commented line [13](https://github.com/elixir-sqlite/exqlite/pull/140/files#diff-10ed172a506448a217903c4ff9ddc9e6044d176b8d3ff409a59602494cf2397dR13)

**Comment by warmwaffles** [comment]
At some point I'd love to at least try to stand up a github action for a windows compile and run the test suite.

**Comment by cw789** [comment]
This is ready now.

**mix compile**
```
Microsoft (R) Program Maintenance Utility Version 14.28.29913.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        del /f /q priv
        erl -noshell -s init stop -eval "io:setopts(standard_io, [{encoding, unicode}]), io:format(\"ERTS_INCLUDE_PATH=~ts/erts-~ts/include/\", [code:root_dir(), erlang:system_info(version)])." > Makefile.auto.win
        nmake -                   -F Makefile.win priv\sqlite3_nif.dll

Microsoft (R) Program Maintenance Utility Version 14.28.29913.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        if NOT EXIST "priv" mkdir "priv"
        cl -DNDEBUG=1 -DSQLITE_OMIT_DEPRECATED=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_RBU=1 -DSQLITE_ENABLE_MATH_FUNCTIONS=1 -DSQLITE_ENABLE_JSON1=1 -DSQLITE_ENABLE_GEOPOLY=1 -DSQLITE_ENABLE_FTS5=1 -DSQLITE_ENABLE_FTS4=1 -DSQLITE_ENABLE_FTS3=1 -DENABLE_UPDATE_DELETE_LIMIT=1 -DENABLE_STAT4=1 -DENABLE_SOUNDEX=1 -DENABLE_LOAD_EXTENSION=1 -DENABLE_FTS3_PARENTHESIS=1 -DALLOW_COVERING_INDEX_SCAN=1 -DSQLITE_DQS=0 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS=1 -DSQLITE_USE_URI=1 -DSQLITE_THREADSAFE=1 -Isqlite3 -Ic_src -EHsc -O2  -I"c:/Users/cw/scoop/apps/erlang/23.3.1/erts-11.2/include/" -LD -MD -Fepriv\sqlite3_nif.dll sqlite3\sqlite3.c c_src\sqlite3_nif.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

sqlite3.c
sqlite3_nif.c
Generating Code...
Microsoft (R) Incremental Linker Version 14.28.29913.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/dll
/implib:priv\sqlite3_nif.lib
/out:priv\sqlite3_nif.dll
sqlite3.obj
sqlite3_nif.obj
   Creating library priv\sqlite3_nif.lib and object priv\sqlite3_nif.exp
```

**mix test**
```
............................................

Finished in 0.3 seconds
44 tests, 0 failures

Randomized with seed 730000
```

> At some point I'd love to at least try to stand up a github action for a windows compile and run the test suite.

Definitely. Probably my windows guide or an Erlang action for windows will help then.

**Pull request merged**
