### PR TITLE
Update to 3.36.0 + update script (closes #152)

### LINKED ISSUE #152: Prepare for upgrade to 3.36.0
https://sqlite.org/releaselog/3_36_0.html

We can remove `-DSQLITE_ENABLE_DESERIALIZE` since that will be enabled by default now.

### PR DESCRIPTION
**Pull request by mindreframer**

### CODE REVIEW

**Review by cw789 — CHANGES_REQUESTED** [review]
Remove `DSQLITE_ENABLE_DESERIALIZE` also in `Makefile.win`.

**Comment by mindreframer** [comment]
@cw789 thanks, totally missed that!

**Comment by kevinlang** [comment]
Thanks for the contribution! I'll update the changelog and cut a release.

**Comment by mindreframer** [comment]
Thanks for the quick merge!

**Pull request merged**
