### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -S c_src,deps`

### CODE REVIEW

**Review by warmwaffles — APPROVED** [review]

**Comment by warmwaffles** [comment]
I wonder if we should add that as a check to the lint action for github actions.

**Comment by kianmeng** [comment]
> I wonder if we should add that as a check to the lint action for github actions.

Your call. :smile:

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by warmwaffles** [comment]
I'll explore it. I think it is worth having.

**Pull request merged**
